import type { ConceptExtraction } from "./types";

export const DEMO_NOTE = `Assessment: hypertension, diabetes mellitus, COPD.
Denies chest pain or shortness of breath at rest.
Family history: breast cancer in mother.`;

export const DEMO_EXTRACTIONS: ConceptExtraction[] = [
  {
    text: "hypertension",
    expanded_text: "hypertension",
    normalized_text: "hypertension",
    cui: "C0020538",
    preferred_term: "Hypertensive disease",
    tui: "T047",
    semantic_type: "Disease or Syndrome",
    semantic_group: "DISO",
    semantic_group_name: "Disorders",
    assertion: "PRESENT",
    subject: "PATIENT",
    score: 0.782,
    rerank_score: 0.816,
    severity: null,
    laterality: null,
    temporality: null,
    start: 12,
    end: 24,
    candidates: [
      {
        rank: 0,
        cui: "C0020538",
        preferred_term: "Hypertensive disease",
        tui: "T047",
        semantic_group: "DISO",
        score: 0.782,
        lex: 0.333,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.816,
      },
      {
        rank: 1,
        cui: "C0020542",
        preferred_term: "Pulmonary Hypertension",
        tui: "T047",
        semantic_group: "DISO",
        score: 0.771,
        lex: 0.500,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.799,
      },
      {
        rank: 2,
        cui: "C1271104",
        preferred_term: "Portal Hypertension",
        tui: "T047",
        semantic_group: "DISO",
        score: 0.748,
        lex: 0.500,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.776,
      },
    ],
  },
  {
    text: "diabetes mellitus",
    expanded_text: "diabetes mellitus",
    normalized_text: "diabetes mellitus",
    cui: "C0011849",
    preferred_term: "Diabetes Mellitus",
    tui: "T047",
    semantic_type: "Disease or Syndrome",
    semantic_group: "DISO",
    semantic_group_name: "Disorders",
    assertion: "PRESENT",
    subject: "PATIENT",
    score: 0.801,
    rerank_score: 0.852,
    severity: null,
    laterality: null,
    temporality: null,
    start: 26,
    end: 42,
    candidates: [
      {
        rank: 0,
        cui: "C0011849",
        preferred_term: "Diabetes Mellitus",
        tui: "T047",
        semantic_group: "DISO",
        score: 0.801,
        lex: 1.0,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.852,
      },
      {
        rank: 1,
        cui: "C0011860",
        preferred_term: "Type 2 Diabetes Mellitus",
        tui: "T047",
        semantic_group: "DISO",
        score: 0.785,
        lex: 0.667,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.823,
      },
      {
        rank: 2,
        cui: "C0011854",
        preferred_term: "Type 1 Diabetes Mellitus",
        tui: "T047",
        semantic_group: "DISO",
        score: 0.772,
        lex: 0.667,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.810,
      },
    ],
  },
  {
    text: "COPD",
    expanded_text: "chronic obstructive pulmonary disease",
    normalized_text: "chronic obstructive pulmonary disease",
    cui: "C0024117",
    preferred_term: "Chronic Obstructive Airway Disease",
    tui: "T047",
    semantic_type: "Disease or Syndrome",
    semantic_group: "DISO",
    semantic_group_name: "Disorders",
    assertion: "PRESENT",
    subject: "PATIENT",
    score: 0.762,
    rerank_score: 0.792,
    severity: null,
    laterality: null,
    temporality: null,
    start: 44,
    end: 48,
    candidates: [
      {
        rank: 0,
        cui: "C0024117",
        preferred_term: "Chronic Obstructive Airway Disease",
        tui: "T047",
        semantic_group: "DISO",
        score: 0.762,
        lex: 0.400,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.792,
      },
      {
        rank: 1,
        cui: "C0155883",
        preferred_term: "COPD with Acute Exacerbation",
        tui: "T047",
        semantic_group: "DISO",
        score: 0.734,
        lex: 0.200,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.758,
      },
    ],
  },
  {
    text: "chest pain",
    expanded_text: "chest pain",
    normalized_text: "chest pain",
    cui: "C0008031",
    preferred_term: "Chest Pain",
    tui: "T184",
    semantic_type: "Sign or Symptom",
    semantic_group: "DISO",
    semantic_group_name: "Disorders",
    assertion: "ABSENT",
    subject: "PATIENT",
    score: 0.744,
    rerank_score: 0.776,
    severity: null,
    laterality: null,
    temporality: null,
    start: 57,
    end: 67,
    candidates: [
      {
        rank: 0,
        cui: "C0008031",
        preferred_term: "Chest Pain",
        tui: "T184",
        semantic_group: "DISO",
        score: 0.744,
        lex: 1.0,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.776,
      },
      {
        rank: 1,
        cui: "C0232289",
        preferred_term: "Chest Discomfort",
        tui: "T184",
        semantic_group: "DISO",
        score: 0.698,
        lex: 0.333,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.726,
      },
    ],
  },
  {
    text: "shortness of breath at rest",
    expanded_text: "shortness of breath at rest",
    normalized_text: "shortness of breath",
    cui: "C0013404",
    preferred_term: "Dyspnea",
    tui: "T184",
    semantic_type: "Sign or Symptom",
    semantic_group: "DISO",
    semantic_group_name: "Disorders",
    assertion: "ABSENT",
    subject: "PATIENT",
    score: 0.698,
    rerank_score: 0.724,
    severity: null,
    laterality: null,
    temporality: "at rest",
    start: 71,
    end: 98,
    candidates: [
      {
        rank: 0,
        cui: "C0013404",
        preferred_term: "Dyspnea",
        tui: "T184",
        semantic_group: "DISO",
        score: 0.698,
        lex: 0.200,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.724,
      },
      {
        rank: 1,
        cui: "C4534568",
        preferred_term: "Dyspnea at Rest",
        tui: "T184",
        semantic_group: "DISO",
        score: 0.682,
        lex: 0.333,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.710,
      },
    ],
  },
  {
    text: "breast cancer",
    expanded_text: "breast cancer",
    normalized_text: "breast cancer",
    cui: "C0006142",
    preferred_term: "Malignant neoplasm of breast",
    tui: "T191",
    semantic_type: "Neoplastic Process",
    semantic_group: "DISO",
    semantic_group_name: "Disorders",
    assertion: "PRESENT",
    subject: "FAMILY",
    score: 0.756,
    rerank_score: 0.788,
    severity: null,
    laterality: null,
    temporality: null,
    start: 119,
    end: 132,
    candidates: [
      {
        rank: 0,
        cui: "C0006142",
        preferred_term: "Malignant neoplasm of breast",
        tui: "T191",
        semantic_group: "DISO",
        score: 0.756,
        lex: 0.333,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.788,
      },
      {
        rank: 1,
        cui: "C0678222",
        preferred_term: "Breast Carcinoma",
        tui: "T191",
        semantic_group: "DISO",
        score: 0.742,
        lex: 0.333,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.774,
      },
    ],
  },
];
