import type { ConceptExtraction } from "./types";

export const DEMO_NOTE = `Assessment: hypertension, diabetes mellitus, COPD.
Denies chest pain or shortness of breath at rest.`;

export const DEMO_EXTRACTIONS: ConceptExtraction[] = [
  {
    text: "hypertension",
    expanded_text: "hypertension",
    normalized_text: "hypertension",
    cui: "C0020538",
    preferred_term: "Hypertensive disease",
    tui: "T047",
    semantic_type: "Disease or Syndrome",
    semantic_group: "DISO",
    semantic_group_name: "Disorders",
    assertion: "PRESENT",
    subject: "PATIENT",
    score: 0.782,
    rerank_score: 0.816,
    severity: null,
    laterality: null,
    temporality: null,
    start: 12,
    end: 24,
    candidates: [
      {
        rank: 0,
        cui: "C0020538",
        preferred_term: "Hypertensive disease",
        tui: "T047",
        semantic_group: "DISO",
        score: 0.782,
        lex: 0.333,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.816,
      },
      {
        rank: 1,
        cui: "C0020542",
        preferred_term: "Pulmonary hypertension",
        tui: "T047",
        semantic_group: "DISO",
        score: 0.771,
        lex: 0.500,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.799,
      },
      {
        rank: 2,
        cui: "C1271104",
        preferred_term: "Portal hypertension",
        tui: "T047",
        semantic_group: "DISO",
        score: 0.748,
        lex: 0.500,
        meets_threshold: true,
        relation_hits: 0,
        bias: 0.018,
        penalty: 0,
        rerank_score: 0.816,
      },
    ],
  },
  {
    text: "diabetes mellitus",
    expanded_text: "diabetes mellitus",
    normalized_text: "diabetes mellitus",
    cui: "C0011849",
    preferred_term: "Diabetes Mellitus",
    tui: "T047",
    semantic_type: "Disease or Syndrome",
    semantic_group: "DISO",
    semantic_group_name: "Disorders",
    assertion: "PRESENT",
    subject: "PATIENT",
    score: 0.801,
    rerank_score: 0.852,
    severity: null,
    laterality: null,
    temporality: null,
    start: 26,
    end: 42,
    candidates: null,
  },
  {
    text: "COPD",
    expanded_text: "chronic obstructive pulmonary disease",
    normalized_text: "chronic obstructive pulmonary disease",
    cui: "C0024117",
    preferred_term: "Chronic Obstructive Airway Disease",
    tui: "T047",
    semantic_type: "Disease or Syndrome",
    semantic_group: "DISO",
    semantic_group_name: "Disorders",
    assertion: "PRESENT",
    subject: "PATIENT",
    score: 0.762,
    rerank_score: 0.792,
    severity: null,
    laterality: null,
    temporality: null,
    start: 44,
    end: 48,
    candidates: null,
  },
  {
    text: "chest pain",
    expanded_text: "chest pain",
    normalized_text: "chest pain",
    cui: "C0008031",
    preferred_term: "Chest Pain",
    tui: "T184",
    semantic_type: "Sign or Symptom",
    semantic_group: "DISO",
    semantic_group_name: "Disorders",
    assertion: "ABSENT",
    subject: "PATIENT",
    score: 0.744,
    rerank_score: 0.776,
    severity: null,
    laterality: null,
    temporality: null,
    start: 57,
    end: 67,
    candidates: null,
  },
];
